# Generated by Django 3.1.1 on 2020-10-01 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameraoverlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_point1x', models.IntegerField(blank=True, default=0)),
                ('camera_point1y', models.IntegerField(blank=True, default=0)),
                ('camera_point2x', models.IntegerField(blank=True, default=0)),
                ('camera_point2y', models.IntegerField(blank=True, default=0)),
                ('camera_point3x', models.IntegerField(blank=True, default=0)),
                ('camera_point3y', models.IntegerField(blank=True, default=0)),
                ('camera_point4x', models.IntegerField(blank=True, default=0)),
                ('camera_point4y', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cameraset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(blank=True, max_length=50)),
                ('camera_no', models.IntegerField(blank=True, default=0)),
                ('camera_link1', models.CharField(blank=True, max_length=200)),
                ('camera_link2', models.CharField(blank=True, max_length=200)),
                ('camera_main', models.CharField(blank=True, max_length=200)),
                ('camera_slave', models.CharField(blank=True, max_length=200)),
                ('camera_point1x', models.IntegerField(blank=True, default=0)),
                ('camera_point1y', models.IntegerField(blank=True, default=0)),
                ('camera_point2x', models.IntegerField(blank=True, default=0)),
                ('camera_point2y', models.IntegerField(blank=True, default=0)),
                ('camera_point3x', models.IntegerField(blank=True, default=0)),
                ('camera_point3y', models.IntegerField(blank=True, default=0)),
                ('camera_point4x', models.IntegerField(blank=True, default=0)),
                ('camera_point4y', models.IntegerField(blank=True, default=0)),
                ('camera_overlay', models.IntegerField(blank=True, default=0)),
                ('camera_detection', models.IntegerField(blank=True, default=0)),
                ('camera_annotation', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Groupcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=50)),
                ('group_no', models.IntegerField(blank=True, default=0)),
                ('group_color', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=150)),
                ('product_supplier', models.CharField(blank=True, max_length=150)),
                ('product_ttvpn', models.CharField(blank=True, max_length=50)),
                ('product_desc', models.TextField(blank=True)),
                ('product_qty', models.IntegerField(blank=True, default=0)),
                ('product_partno', models.CharField(blank=True, max_length=150)),
                ('product_oum', models.CharField(blank=True, max_length=20)),
                ('product_location', models.TextField(blank=True, max_length=50)),
                ('product_jobno', models.CharField(blank=True, max_length=150)),
                ('product_currency', models.CharField(blank=True, max_length=10)),
                ('product_febexcrate', models.CharField(blank=True, max_length=10)),
                ('product_totalprice', models.CharField(blank=True, max_length=10)),
                ('product_pricefrom', models.CharField(blank=True, max_length=30)),
                ('product_company', models.CharField(blank=True, max_length=30)),
                ('product_ponumbers', models.CharField(blank=True, max_length=30)),
                ('product_invoice', models.CharField(blank=True, max_length=30)),
                ('product_invdate', models.CharField(blank=True, max_length=30)),
                ('product_remarks', models.CharField(blank=True, max_length=150)),
                ('product_photo', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ttvproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=150)),
                ('p_company', models.CharField(blank=True, max_length=100)),
                ('p_code', models.CharField(blank=True, max_length=150)),
                ('p_model', models.CharField(blank=True, max_length=150)),
                ('p_desc', models.CharField(blank=True, max_length=150)),
                ('p_startdate', models.CharField(blank=True, max_length=150)),
                ('p_enddate', models.CharField(blank=True, max_length=150)),
                ('p_status', models.CharField(blank=True, max_length=150)),
                ('p_type', models.CharField(blank=True, max_length=150)),
                ('p_comp', models.CharField(blank=True, max_length=150)),
                ('p_userid', models.IntegerField(blank=True, default=0)),
                ('p_color', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ttvcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(blank=True, max_length=100)),
                ('cell_size', models.IntegerField(blank=True, default=0)),
                ('cell_lane', models.IntegerField(blank=True, default=0)),
                ('cell_status', models.CharField(blank=True, max_length=10)),
                ('cell_color', models.CharField(blank=True, max_length=10)),
                ('cell_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashapp.groupcell')),
                ('cell_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashapp.ttvproject')),
            ],
        ),
        migrations.CreateModel(
            name='Cctvline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_line_name', models.CharField(blank=True, max_length=50)),
                ('point_one', models.CharField(blank=True, max_length=50)),
                ('point_two', models.CharField(blank=True, max_length=50)),
                ('point_three', models.CharField(blank=True, max_length=50)),
                ('point_four', models.CharField(blank=True, max_length=50)),
                ('camera_relate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashapp.cameraset')),
            ],
        ),
        migrations.CreateModel(
            name='Cctvgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgroup_name', models.CharField(blank=True, max_length=100)),
                ('cgroup_much', models.IntegerField(blank=True, default=0)),
                ('cgroup_link', models.CharField(blank=True, max_length=200)),
                ('cgroup_cardcolor', models.CharField(blank=True, max_length=30)),
                ('cgroup_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashapp.ttvcell')),
            ],
        ),
        migrations.AddField(
            model_name='cameraset',
            name='camera_cell_tag',
            field=models.ManyToManyField(to='dashapp.Ttvcell'),
        ),
        migrations.AddField(
            model_name='cameraset',
            name='camera_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashapp.cctvgroup'),
        ),
    ]
